### ISSUE TITLE
Gif Size

### ISSUE THREAD

**Issue by masonhensley** [ThasianX/ElegantTimeline-SwiftUI#7]
Hello! Very cool project.

One FYI, the readme page has some very large GIF's in it that would potentially destroy a mobile data plan.

Some other users have recommendations about converting the images here. https://news.ycombinator.com/item?id=23881539

Thanks for sharing with the community 🤓 

Screenshot from chrome dev inspector:

![image](https://user-images.githubusercontent.com/534165/87858302-eb1ac200-c8fa-11ea-9fbf-baf58307ada6.png)

**Comment by ThasianX** [comment]
Working on it now. Converting them to embeded videos

**Comment by ThasianX** [comment]
Fixed on master
